<STYLE TYPE="text/css">
<!--
	body { font-family: "Calibri", "Arial", "Helvetica", sans-serif; font-size: 11pt; so-language: es-ES }
	@page { margin: 2.5cm }
	P { margin-bottom: 0.21cm; direction: ltr; color: #000000; line-height: 115%; widows: 2; orphans: 2 }
	P.western { font-family: "Calibri", "Arial", "Helvetica", sans-serif; font-size: 11pt; so-language: es-ES }
	P.cjk { font-family: "Calibri", "Arial", "Helvetica", sans-serif; font-size: 11pt }
	P.ctl { font-family: "Calibri", "Arial", "Helvetica", sans-serif; font-size: 11pt; so-language: ar-SA }
	TABLE { margin-top: 20pt; }
-->
</STYLE>
<P LANG="es-ES" STYLE="margin-bottom: 0cm; line-height: 100%"> <IMG SRC="/janium/Imagenes/logos/plantilla_paz_y_salvo_igac_01.png" NAME="graficos2" ALIGN=LEFT HSPACE=1 WIDTH=85 HEIGHT=86 BORDER=0><IMG SRC="/janium/Imagenes/logos/plantilla_paz_y_salvo_igac_02.png" NAME="graficos1" ALIGN=LEFT HSPACE=1 WIDTH=69 HEIGHT=81 BORDER=0>
                        <FONT SIZE=4><B>&nbsp;&nbsp;INSTITUTO GEOGRÁFICO AGUSTÍN
CODAZZI</B></FONT><BR>&nbsp;       
                                                          <FONT SIZE=2><B>S
E D E &nbsp; C E N T R A L</B></FONT></P>
<P LANG="es-ES" STYLE="margin-bottom: 0cm; line-height: 100%"><BR>
</P>
<P LANG="es-ES" STYLE="margin-bottom: 0cm; line-height: 100%"><BR>
</P>
<CENTER>
<TABLE WIDTH=632 BORDER=1 BORDERCOLOR="#000000" CELLPADDING=8 CELLSPACING=0>
	<COL WIDTH=445>
	<COL WIDTH=36>
	<COL WIDTH=40>
	<COL WIDTH=44>
	<TR VALIGN=TOP>
		<TD ROWSPAN=3 WIDTH=445 HEIGHT=2>
			<P LANG="es-ES" ALIGN=CENTER STYLE="margin-bottom: 0cm"><FONT SIZE=3><B>CONTROL &nbsp;
			ADMINISTRATIVO</B></FONT></P>
			<P LANG="es-ES" ALIGN=CENTER><FONT SIZE=2><B>INSTITUTO GEOGRÁFICO
			AGUSTÍN CODAZZI</B></FONT></P>
		</TD>
		<TD COLSPAN=3 WIDTH=152>
			<P LANG="es-ES" ALIGN=CENTER><FONT SIZE=2><B>FECHA</B></FONT></P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=36>
			<P LANG="es-ES" ALIGN=CENTER STYLE="margin-bottom: 0cm"><BR>
			</P>
			<P LANG="es-ES" ALIGN=CENTER><FONT SIZE=2><B>DD</B></FONT></P>
		</TD>
		<TD WIDTH=40>
			<P LANG="es-ES" ALIGN=CENTER STYLE="margin-bottom: 0cm"><BR>
			</P>
			<P LANG="es-ES" ALIGN=CENTER><FONT SIZE=2><B>MM</B></FONT></P>
		</TD>
		<TD WIDTH=44>
			<P LANG="es-ES" ALIGN=CENTER STYLE="margin-bottom: 0cm"><BR>
			</P>
			<P LANG="es-ES" ALIGN=CENTER><FONT SIZE=2><B>AA</B></FONT></P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=36>
			<P LANG="es-ES" ALIGN=CENTER>
				<input type="text" value="DD" maxlength="2" size="2">
			</P>
		</TD>
		<TD WIDTH=40>
			<P LANG="es-ES" ALIGN=CENTER STYLE="margin-bottom: 0cm">
				<input type="text" value="MM" maxlength="2" size="2">
			</P>
		</TD>
		<TD WIDTH=44>
			<P LANG="es-ES" ALIGN=CENTER>
				<input type="text" value="AA" maxlength="2" size="2">
			</P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=445 HEIGHT=24>
			<P LANG="es-ES"><FONT SIZE=2><B>NOMBRES Y APELLIDOS</B></FONT><BR>
			</P>
			<P LANG="es-ES"><BR>
				::NOMBRE::
			</P>
		</TD>
		<TD COLSPAN=3 WIDTH=152>
			<P LANG="es-ES" STYLE="margin-bottom: 0cm"><FONT SIZE=2><B>IDENTIFICACIÓN</B></FONT><BR>
			</P>
			<P LANG="es-ES"><BR>
				::NOCUENTA:: / ::IDALTERNO::
			</P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD ROWSPAN=2 WIDTH=445 HEIGHT=8>
			<P LANG="es-ES" STYLE="margin-bottom: 0cm"><FONT SIZE=2><B>DEPENDENCIA</B></FONT></P>
			<P LANG="es-ES"><BR>
				::CAT1:: / ::CAT2::
			</P>
		</TD>
		<TD COLSPAN=3 WIDTH=152>
			<P LANG="es-ES"><FONT SIZE=2><B>PLANTA</B></FONT></P>::CODPERFIL:: / ::PERFIL::
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD COLSPAN=3 WIDTH=152>
			<P LANG="es-ES"><FONT SIZE=2><B>CONTRATO</B></FONT></P>::OPERADOR::
		</TD>
	</TR>
	<TR>
		<TD COLSPAN=4 WIDTH=614 HEIGHT=7 VALIGN=TOP>
			<P LANG="es-ES"><FONT SIZE=2 STYLE="font-size: 9pt">Nosotros los
			abajo firmantes certificamos que el (la) señor (a) anteriormente
			relacionado (a) se encuentra a Paz y Salvo en la Biblioteca.</FONT></P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=445 HEIGHT=6>
			<P LANG="es-ES" STYLE="margin-bottom: 0cm"><FONT SIZE=2><B>BIBLIOTECA</B></FONT><BR><BR>::CODBIBLIOTECA:: / ::BIBLIOTECA::<BR><BR></P>
			<P LANG="es-ES"><FONT SIZE=2 STYLE="font-size: 9pt"><B>CLARA M.
			GIRÓN GIRÓN</B></FONT></P>
		</TD>
		<TD COLSPAN=3 WIDTH=152>
			<P LANG="es-ES"><FONT SIZE=2 STYLE="font-size: 9pt"><B>FIRMA</B></FONT></P>
		</TD>
	</TR>
</TABLE>
<P LANG="es-ES" STYLE="margin-bottom: 0cm; line-height: 100%"><BR>
</P>
<P LANG="es-ES" STYLE="margin-bottom: 0cm; line-height: 100%"><BR>
</P>
<P LANG="es-ES" STYLE="margin-bottom: 0cm; line-height: 100%"><BR>
</P>
<P LANG="es-ES" CLASS="western" ALIGN=CENTER STYLE="margin-bottom: 0.35cm">
<BR><BR>
</P>
<P LANG="es-ES" ALIGN=CENTER STYLE="margin-bottom: 0cm; line-height: 100%">
B O G O T Á &nbsp; D . C .</P>
<P LANG="es-ES" ALIGN=CENTER STYLE="margin-bottom: 0cm; line-height: 100%">
<FONT SIZE=1>Carrera 30 No. 48-51 Conmutador 3694000 -3694100 Fax
3694098 Información al cliente 3683443 &mdash; 3694000 Ext. 4674 web:
www.igac.gov.co</FONT></P>
<P LANG="es-ES" CLASS="western" ALIGN=CENTER STYLE="margin-bottom: 0.35cm">
<FONT SIZE=2 STYLE="font-size: 9pt">Sistema de Gestión de Calidad
Certificado</FONT></P>
</CENTER>
